/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIX509Cert;

[scriptable, uuid(9702fdd4-4c2c-439c-ba2e-19cda018eb99)]
interface nsIDevToolsCertService : nsISupports
{
  nsIX509Cert getOrCreateCert();
};
