/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIServerSocket.idl"

interface nsIX509Cert;
interface nsITLSSecurityCallback;

/**
 * nsITLSServerSocket
 *
 * An interface to a TLS server socket that can accept incoming connections.
 */
[scriptable, uuid(2e025b6c-96ba-4781-85fb-d1cf1a653207)]
interface nsITLSServerSocket : nsIServerSocket
{
  /**
   * serverCert
   *
   * The server's certificate that is preseneted to the client during the TLS
   * handshake.  This is required to be set before calling |asyncListen|.
   */
  attribute nsIX509Cert serverCert;

  /**
   * sessionCache
   *
   * Whether the server should use a session cache.  Defaults to true.
   */
  attribute boolean sessionCache;

  /**
   * sessionTickets
   *
   * Whether the server should use support session tickets.  Defaults to true.
   */
  attribute boolean sessionTickets;

  /**
   * requestCertificate
   *
   * Whether the server should request and/or require a client auth certificate
   * from the client.  Defaults to REQUEST_NEVER.  See the possible options
   * below.
   */
  attribute unsigned long requestCertificate;

  /**
   * Values for requestCertificate
   * TODO: More comments
   */
  const unsigned long REQUEST_NEVER           = 0;
  const unsigned long REQUEST_FIRST_HANDSHAKE = 1;
  const unsigned long REQUEST_ALWAYS          = 2;
  const unsigned long REQUIRE_FIRST_HANDSHAKE = 3;
  const unsigned long REQUIRE_ALWAYS          = 4;
};
